/* eslint-disable react/no-unescaped-entities */
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Tsukuba Express Simulator',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <style>
        @import url('https://fonts.googleapis.com/css2?family=Rajdhani&display=swap');
      </style>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
